### ISSUE TITLE
Sort by rating should use a more fair algorithm

### ISSUE THREAD

**Issue by kannes** [Xpirix/QGIS-Plugins-Website#21]
Sorting by stars considers a single 5 star rating to be "better" than 3000 ratings with an average of 4.9. Technically true (=average) but also making sorting by stars completely useless. :D

It's a common issue and https://www.evanmiller.org/how-not-to-sort-by-average-rating.html is a popular article with a great alternative algorithm.

It would be great if the sorting by stars could use such a fair algorithm.

**Comment by Xpirix** [comment]
That's right! Thanks for the hint about the Wilson score. 

I found (and applied) a similar solution using the Bayesian average in the custom ranking (https://www.algolia.com/doc/guides/managing-results/must-do/custom-ranking/how-to/bayesian-average/). I think the Bayesian average is more appropriate for the plugins staring is based on the average rating and the number of votes.

https://github.com/Xpirix/QGIS-Plugins-Website/blob/9f22dc2133c2b2aaae02ad29edfe04e810fb4ce8/qgis-app/plugins/models.py#L34-L35

https://github.com/Xpirix/QGIS-Plugins-Website/blob/9f22dc2133c2b2aaae02ad29edfe04e810fb4ce8/qgis-app/plugins/models.py#L51-L55

**Comment by kannes** [comment]
Yeah, I use the bayesian average too on some project of mine and I have no idea about the difference. It works really well!
