### ISSUE TITLE
Show number of pages in pagination

### ISSUE THREAD

**Issue by kannes** [Xpirix/QGIS-Plugins-Website#22]
The pagination bar only shows textual descriptions for "First" and "Last", no "1" and (e.g.) "32". On the first page it can appear like only 3 pages exist, because only 1, 2 and 3 are named with buttons.

It would be great to have the first and last page shown with their number too.

![image](https://github.com/user-attachments/assets/ade8157b-3c5c-4266-bf7a-4b9b2233d7c1)

I am not sure where it would be best, maybe on the First and Last buttons directly, or with additional buttons if space permits?

![image](https://github.com/user-attachments/assets/d0e59e24-b8d5-4106-a436-a191cec388bd)

Maybe it is a stupid idea :)

**Comment by Xpirix** [comment]
Hi @kannes,

It's a good idea. I suggest showing the first and last page numbers as additional buttons and removing the First and Last buttons. Here is a screenshot of the update:

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/e89cc6bd-e0c6-4778-baf8-3b321a83aad5">

**Comment by kannes** [comment]
That looks great!
